// Type definitions for plastic-io 2.1.0
// Project: plastic-io
// Definitions by: Tony Germaneri https://github.com/plastic-io
import {
    LoadEvent,
    Connector,
    FieldMap,
    NodeTemplate,
    LinkedNode,
    LinkedGraph,
    NodeInterface,
    NodeSetEvent,
    Logger,
    Graph,
    newId,
    GraphProperties,
    ExecutionResult,
    ConnectorEvent,
    SchedulerEvent,
    EdgeError,
    Warning,
    HostInterface,
    ObservationEvent,
    SchedulerOptions,
    ContractHook,
    EventIds,
} from "./Shared";
import Scheduler from "./Scheduler";
import Edge from "./Edge";
import Node, {linkInnerNodeEdges, getLinkedInputs, compile} from "./Node";
import Loader from "./Loader";
import {
    GraphInstance,
    LinkedGraphDepthError,
    DEFAULT_LINKED_GRAPH_DEPTH,
    instanceOf,
    instancePathOf,
} from "./Instances";
import {
    Execution,
    ExecutionCancelled,
    CancellationToken,
    DEFAULT_BUDGET,
    ExecutionHandle,
    BudgetSpec,
    BudgetView,
    ExecutionState,
    Span,
} from "./Execution";
export default Scheduler;
export {
    getLinkedInputs,
    linkInnerNodeEdges,
    compile,
    Loader,
    Node,
    Edge,
    LoadEvent,
    Connector,
    FieldMap,
    NodeTemplate,
    LinkedNode,
    LinkedGraph,
    NodeInterface,
    NodeSetEvent,
    Logger,
    Graph,
    newId,
    GraphProperties,
    ExecutionResult,
    SchedulerEvent,
    ConnectorEvent,
    EdgeError,
    Warning,
    Execution,
    ExecutionCancelled,
    CancellationToken,
    DEFAULT_BUDGET,
    ExecutionHandle,
    BudgetSpec,
    BudgetView,
    ExecutionState,
    Span,
    HostInterface,
    ObservationEvent,
    SchedulerOptions,
    ContractHook,
    EventIds,
    // Linked graphs as calls (2.3): one instance per use, named by the path
    // of hosts it was reached through.
    GraphInstance,
    LinkedGraphDepthError,
    DEFAULT_LINKED_GRAPH_DEPTH,
    instanceOf,
    instancePathOf,
}
