name: Tests

on:
  push:
    branches:
      - master

jobs:
    build:
      - name: Tests
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: peaceiris/actions-gh-pages@v3
        - uses: actions/setup-node@v1
          with:
            node-version: '10.x'
          run: npm install
          run: npm run build
          run: npm test
          run: npm run build-docs
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          publish_dir: ./docs
